export { default as Dashboard } from './Dashboard';
export { default as Consumables } from './Consumables';
export { default as  Equipments} from './Equipments';
export { default as  Employees} from './Employees';
export { default as Customers} from './Customers';
export { default as  PO} from './Po';
export { default as  WO} from './Wo';
export { default as Registration} from './Registration';
export { default as AddPO} from './AddPo';
export { default as AddWO} from './AddWo';
export { default as AddCustomer} from './AddCustomer';