export { default as Dashboard } from './Dashboard';
export { default as Consumables } from './Consumables';
export { default as  Equipments} from './Equipments';
export { default as  Employees} from './Employees';
export { default as Customers} from './Customers';
export { default as  PO} from './Po';
export { default as  WO} from './Wo';
export { default as Registration} from './Registration';
export { default as AddPO} from './AddPo';
export { default as AddWO} from './AddWo';
export { default as AddCustomer} from './AddCustomer';
export { default as Timecard} from './TimeCard';
export { default as Login} from './Login';
export { default as UserProfile} from './UserProfile';
export { default as Page404} from './page404';
export { default as EquipProfile} from './EquipProfile';
export { default as ConsProfile} from './ConsProfile';
export { default as PoProfile} from './PoProfile';
export { default as WoProfile} from './WoProfile';
export { default as CustomerProfile} from './CustomerProfile';